"""Add Project model and relationship to Task

Revision ID: 3b6c60669e48
Revises: ec70eaafa7b6
Create Date: 2025-12-19 03:46:01.389687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3b6c60669e48'
down_revision: Union[str, Sequence[str], None] = 'ec70eaafa7b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_user_id'), 'project', ['user_id'], unique=False)
    op.add_column('task', sa.Column('project_id', sa.Uuid(), nullable=True))
    op.create_index(op.f('ix_task_project_id'), 'task', ['project_id'], unique=False)
    op.create_foreign_key(None, 'task', 'project', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.drop_index(op.f('ix_task_project_id'), table_name='task')
    op.drop_column('task', 'project_id')
    op.drop_index(op.f('ix_project_user_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###