"""Add due_date field to Task model

Revision ID: 4ac448e3f100
Revises: 3b6c60669e48
Create Date: 2025-12-19 03:50:35.687835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ac448e3f100'
down_revision: Union[str, Sequence[str], None] = '3b6c60669e48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('due_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'due_date')
    # ### end Alembic commands ###
